const {JSDOM} = require('jsdom');
const fs = require('fs');
const assert = require('assert');
const path = require('path');
const script = fs.readFileSync(path.join(__dirname, '../custom_components/interstellar_network/frontend/interstellar-network-card.js'), 'utf8');
const dom = new JSDOM('<html><body></body></html>', {runScripts:'dangerously', url:'http://localhost'});
dom.window.eval(script);
assert.equal(dom.window.interstellarNetworkCardVersion, '0.4.1');
assert(dom.window.customElements.get('interstellar-overview-card'));
assert(dom.window.customElements.get('interstellar-network-card'));
const legacyDom = new JSDOM('<html><body></body></html>', {runScripts:'dangerously', url:'http://localhost'});
legacyDom.window.customElements.define('interstellar-network-card', class extends legacyDom.window.HTMLElement {});
assert.doesNotThrow(() => legacyDom.window.eval(script));
assert(legacyDom.window.customElements.get('interstellar-overview-card'));
const card = dom.window.document.createElement('interstellar-overview-card');
dom.window.document.body.append(card);
card.setConfig({default_expanded:true});
const snapshot = (id,name,health=true,wake=false,control=true) => ({state:health?'online':'offline',attributes:{interstellar_network_id:id,interstellar_key:'server_snapshot',interstellar_hostname:name,snapshot:{host:{machine_id:id,hostname:name,roles:['development'],uptime_seconds:90000,os:'Debian'},timestamp_utc:new Date().toISOString(),cpu:{used_percent:42},memory:{used_percent:50,total_bytes:1000,used_bytes:500},disk_root:{used_percent:30,total_bytes:1000,used_bytes:300},updates:{pending:2,pending_security:1,packages:[]},system:{reboot_required:false,failed_systemd_units:0},service_policy:{expected_services:['ssh'],problems:[]},services:{ssh:'active'},network:{addresses:[{kind:'lan',address:'192.168.1.2'}]},wake_on_lan:{configured:wake,mac_address:'aa:bb:cc:dd:ee:fe',broadcast_address:'192.168.1.255'},control:{available:control,policy:{manageable_services:[],manageable_containers:[]},actions:[]}}}});
card.hass={states:{'sensor.atlas_snapshot':snapshot('a','Atlas'),'sensor.jupiter_snapshot':snapshot('j','Jupiter')},callService:async()=>{}};
assert(card.shadowRoot.textContent.includes('2 servers'));
assert(card.shadowRoot.textContent.includes('Atlas'));
assert(card.shadowRoot.querySelectorAll('details.server').length===2);
assert(card.shadowRoot.querySelector('details.server').open);
assert(card.shadowRoot.textContent.includes('Security'));
assert.equal(card.shadowRoot.querySelectorAll('[data-action="restart_tailscaled"]').length,0);
card.shadowRoot.querySelector('[data-filter="offline"]').click();
assert(card.shadowRoot.textContent.includes('No matching servers'));
card.shadowRoot.querySelector('[data-filter="all"]').click();
card.hass={states:{'sensor.atlas_snapshot':snapshot('a','Atlas',false)},callService:async()=>{}};
assert(card.shadowRoot.textContent.includes('offline'));
assert.equal(card.shadowRoot.querySelectorAll('[data-action="wake"]').length,0);
assert.equal(card.shadowRoot.querySelectorAll('[data-action="shutdown"]').length,0);
card.hass={states:{'sensor.atlas_snapshot':snapshot('a','Atlas',false,true)},callService:async()=>{}};
assert(card.shadowRoot.textContent.includes('Wake-on-LAN available'));
assert(card.shadowRoot.querySelector('[data-action="wake"]'));
assert.equal(card.shadowRoot.querySelectorAll('[data-action="reboot"]').length,0);
const malicious=snapshot('x','<script>alert(1)</script>');
card.hass={states:{'sensor.malicious':malicious},callService:async()=>{}};
assert.equal(card.shadowRoot.querySelectorAll('script').length,0);
assert(card.shadowRoot.textContent.includes('<script>alert(1)</script>'));
assert(script.includes('@media(max-width:600px)'));
(async()=>{
  const calls=[];
  card.hass={states:{'sensor.atlas_snapshot':snapshot('a','Atlas')},callService:async(...args)=>calls.push(args)};
  assert(card.shadowRoot.textContent.includes('Managed'));
  const dialog=card.shadowRoot.querySelector('dialog');
  dialog.showModal=()=>{};
  card.shadowRoot.querySelector('[data-action="reboot"]').click();
  assert.equal(dialog.querySelector('.confirm-label').hidden,false);
  dialog.returnValue='confirm';
  await dialog.onclose();
  assert.equal(calls.length,0);
  dialog.querySelector('#confirm-input').value='Atlas';
  await dialog.onclose();
  assert.equal(calls.length,1);
  assert.equal(calls[0][2].confirmation,'Atlas');
  card.hass={states:{'sensor.atlas_snapshot':snapshot('a','Atlas',true,false,false)},callService:async(...args)=>calls.push(args)};
  assert(card.shadowRoot.textContent.includes('Read-only'));
  card.hass={states:{'sensor.atlas_snapshot':snapshot('a','Atlas')},callService:async(...args)=>calls.push(args)};
  const dialogNoWake=card.shadowRoot.querySelector('dialog');dialogNoWake.showModal=()=>{};
  card.shadowRoot.querySelector('[data-action="shutdown"]').click();
  assert(dialogNoWake.querySelector('#confirm-text').textContent.includes('physical or external access'));
  card.hass={states:{'sensor.atlas_snapshot':snapshot('a','Atlas',true,true)},callService:async(...args)=>calls.push(args)};
  const dialogWithWake=card.shadowRoot.querySelector('dialog');dialogWithWake.showModal=()=>{};
  card.shadowRoot.querySelector('[data-action="shutdown"]').click();
  assert(dialogWithWake.querySelector('#confirm-text').textContent.includes('Wake-on-LAN is configured'));
  dom.window.setTimeout=()=>0;
  card.hass={states:{'sensor.atlas_snapshot':snapshot('a','Atlas',false,true)},callService:async(...args)=>calls.push(args)};
  card.shadowRoot.querySelector('[data-action="wake"]').click();
  await new Promise(resolve=>setImmediate(resolve));
  assert.equal(calls.at(-1)[1],'wake');
  assert(card.shadowRoot.textContent.includes('Waking'));
  assert(card.shadowRoot.textContent.includes('Wake packet sent'));
  card.hass={states:{'sensor.atlas_snapshot':snapshot('a','Atlas',true,true)},callService:async(...args)=>calls.push(args)};
  assert(!card.shadowRoot.textContent.includes('Waking'));
  console.log('card render, offline wake, feedback, read-only, shutdown warning, escaping, responsive CSS, power confirmation: OK');
})().catch(e=>{console.error(e);process.exitCode=1});
